# -*- coding: utf-8 -*-
"""AnalisisDEscriptivo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZGRzN0r7CZpgkOWcrQh6IPl2eDZLwNJv
"""

#Importando las librerias necesarias 
from google.colab import drive
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats

import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

#Accediendo al archhivo csv del INPC en el periodo (Completar)
drive.mount('/content/drive')

#Asignando el arhivo a una variable
df=('/content/drive/MyDrive/MLenColab/Proyecto ErenInteligencia/INPC-8.csv')

#Creando el DataFrame con la libreria pandas
dfinpc = pd.read_csv(df)
dfinpc

"""Limpiando el DataFrame del INPC eliminando los datos no ncesarios."""

#Eliminando las filas no deseadas
dfinpc = dfinpc.drop(range(0,16))
dfinpc

#Renombrando las columnas
dfinpc = dfinpc.rename(columns={'Instituto Nacional de Estadística y Geografía' : 'Fecha',
                                'Unnamed: 1' : 'INPC_Total',
                                'Unnamed: 2' : 'AlimenBebidNoAlcoholic',
                                'Unnamed: 3' : 'Alcohol&Tabaco',
                                'Unnamed: 4' : 'Vestido&Calzado',
                                'Unnamed: 5' : 'ServicPublideSuministro',
                                'Unnamed: 6' : 'Mobiliario',
                                'Unnamed: 7' : 'Salud',
                                'Unnamed: 8' : 'Transporte',
                                'Unnamed: 9' : 'Comunicaciones',
                                'Unnamed: 10' : 'Recreacion&Cultura',
                                'Unnamed: 11' : 'Educacion',
                                'Unnamed: 12' : 'Restaurant&Hotel',
                                'Unnamed: 13' : 'Diversos'})
dfinpc

#Quitando la columna de Fecha con el fin de tratar mejor la informacion
dfinpc = dfinpc.drop('Fecha', axis = 1)
dfinpc

#Reiniciando los indices para tener un manejo del DataFrame mas facil de manipular
dfinpc.reset_index(drop=True, inplace=True)
dfinpc

#Convirtiendo los datos del dataframe en datos numericos
dfinpc= dfinpc.applymap(lambda x: pd.to_numeric(x, errors='coerce'))
dfinpc

#Redondeando los datos de mi DataFrame a 2 decimales
dfinpc = dfinpc.round(2)
dfinpc

from google.colab import files
dfinpc.to_excel('INPC.xlsx', index = False)
files.download('INPC.xlsx')

dfinpc.to_csv('INPC.csv', encoding = 'utf-8-sig', index = False) 
files.download('INPC.csv')

#Analizando nuestro DataFrame del INPC
dfinpc.describe()